stages:
  - build
  - test

build:
  needs: []
  stage: build
  image: ubuntu:noble
  before_script:
    - apt update
    - apt install -y gcovr git cmake g++ make libssl-dev

  script:
    - cmake -B build
    - cd build
    - make

test:
  needs: []
  stage: test
  image: ubuntu:noble
  before_script:
    - apt update
    - apt install -y gcovr git cmake g++ make libssl-dev
    - cmake -B build -DBUILD_TESTS=ON -DTEST_COVERAGE=ON
    - cd build
    - make

  script:
    - ctest --output-junit report.xml
    - make coverage

  coverage: /^TOTAL.*\s+(\d+\%)$/
  artifacts:
    when: always
    reports:
      junit: build/report.xml
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.xml
    paths:
      - build/coverage.xml
      - build/report.xml
