stages:
  - build
  - tests

build:
  stage: build
  image: ubuntu:noble
  before_script:
    - apt update
    - apt install -y gcovr git cmake g++ make libssl-dev

  script:
    - cmake -B build -DMODBUS_SERVER_GIT_REPO=https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/frickly-systems/pionix/amperfied/modbus-server.git -DGOOSE_LIB_GIT_REPO=https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/frickly-systems/pionix/amperfied/goose-lib.git
    - cd build
    - make

tests:
  stage: tests
  image: ubuntu:noble
  before_script:
    - apt update
    - apt install -y gcovr git cmake g++ make libssl-dev

  script:
    - cmake -B build -DBUILD_TESTS=ON -DTEST_COVERAGE=OFF -DMODBUS_SERVER_GIT_REPO=https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/frickly-systems/pionix/amperfied/modbus-server.git -DGOOSE_LIB_GIT_REPO=https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/frickly-systems/pionix/amperfied/goose-lib.git
    - cd build
    - make
    - ctest --output-junit results.xml

  artifacts:
    when: always
    paths:
      - build/results.xml
    reports:
      junit: build/results.xml
